export default {
  ACTION_LOAD_SETTINGS: 'ACTION_LOAD_SETTINGS',

  LOAD_SETTINGS_START: 'LOAD_SETTINGS_START',
  LOAD_SETTINGS_SUCCESS: 'LOAD_SETTINGS_SUCCESS',
  LOAD_SETTINGS_ERROR: 'LOAD_SETTINGS_ERROR'
};
